[[source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true

[dev-packages]
bandit = "==1.6.2"
black = "==22.3.0"
coverage = "~=5.0"
parameterized = "==0.7.0"
prospector = "==1.1.6.2" #  Our project only works with version 1.1.6.2
isort = "==5.10.1"
django-extensions = "*"
ipdb = "*"
pytest = "*"
pytest-django = "*"
pytest-cov = "*"
requests-mock = "*"
flower = "==1.2"

[packages]
djangorestframework = "~=3.9"
django-background-tasks = "~=1.2"
django-environ = "~=0.4"
django-model-utils = "~=4.0"
sentry-sdk = "~=0.16"
typed-ast = "~=1.4.2"
mohawk = ">=1.1"
python-dateutil = "~=2.8"
requests = "~=2.21"
unidecode = "~=1.2"
django-log-formatter-ecs = "==0.0.5"
gunicorn = "*"
django = "==3.2.16"
elastic-apm = "==6.7.2"
django-jsonfield = "==1.4"
msal = "~=1.18.0"
psycopg2-binary = "~=2.9.3"
setuptools = "~=65.5.1"
celery = {version = "==5.2.7", extras = ["redis"]}
# Celery calls entry_points().get() in a lot of places and that has been removed from later versions of importlib-metadata
# celery 5.3.0 should have fixed all of these calls, when that happens remove importlib-metadata as a dependency.
# https://importlib-metadata.readthedocs.io/en/latest/history.html#v5-0-0
importlib-metadata = "==4.13.0"

[requires]
python_version = "3.7"
